version: "2"
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - errorlint
    - exhaustive
    - gocyclo
    - gosec
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
  settings:
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
